// This file is generated by Slice Machine. Update with care!

import Project from './Project';
import Test from './Test';

export {
	Project,
	Test,
};

export const components = {
	project: Project,
	test: Test,
};
